git:
  depth: false
  quiet: true
  submodules: false

branches:
  only:
    - master

script:
  - "make build"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "S3 Bucket"
  skip_cleanup: true
  local_dir: public
  upload-dir: reisinger.co.uk
