language: minimal

git:
  depth: false
  quiet: true
  submodules: true

branches:
  only:
    - master

script:
  - "make build"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: reisinger.co.uk
  region: eu-west-2
  skip_cleanup: true
  local_dir: ./public
  verbose: true
